<?php
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

//$block = $block ?? $this->getLayout()->getBlock('llmstxt.data');
//$data = $block->getData('generatedData')->getCollectedData();

$data = $block->getViewModel()->getCollectedData();
?>
<?php if ($data['store_name']) : ?>
# <?= $data['store_name'] ?>
<?php endif; ?>

> <?= $data['home_page_meta_title'] ?>


## <?= __('Store Information') ?>

<?php if (!empty($data['cms_pages'])): ?>
<?php foreach ($data['cms_pages'] as $page): ?>
- [<?= $page['title'] ?>](<?= $page['url'] ?>)<?php if (!empty($page['meta_description'])): ?> : <?= $page['meta_description'] ?><?php endif; ?><?= PHP_EOL ?>
<?php endforeach; ?>
<?php endif; ?>

## <?= __('Shop Categories') ?>

### <?= __('Main Categories') ?>

<?php if (!empty($data['categories'])): ?>
<?php foreach ($data['categories'] as $cat): ?>
- [<?= $cat['name'] ?>](<?= $cat['url'] ?>)<?php if (!empty($cat['description'])): ?> : <?= $cat['description'] ?><?php endif; ?><?= PHP_EOL ?>
<?php endforeach; ?>
<?php endif; ?>

## <?= __('Featured Products') ?>

<?php foreach ($data['products'] as $product): ?>
- [<?= $product['name'] ?>](<?= $product['url'] ?>)<?php if (!empty($product['description'])): ?> : <?= $product['description'] ?><?php endif; ?><?= PHP_EOL ?>
<?php endforeach; ?>

<?php if (!empty($data['point_of_sales'])): ?>
## <?= $escaper->escapeHtml(__('Physical Stores')) . PHP_EOL . PHP_EOL ?>

<?= $escaper->escapeHtml(__('Store locator')) ?>: <?= $escaper->escapeUrl($data['store_url'] . 'pointofsale') . PHP_EOL . PHP_EOL ?>

<?php foreach ($data['point_of_sales'] as $pos): ?>
### <?= $escaper->escapeHtml($pos['name']) ?> ###<?= PHP_EOL ?>
- <?= $escaper->escapeHtml(__('Address')) ?>: <?= $escaper->escapeHtml($pos['address']) ?><?= PHP_EOL ?>
- <?= $escaper->escapeHtml(__('Opening Hours')) ?>: <?= $escaper->escapeHtml($pos['opening_hours']) ?><?= PHP_EOL ?>
- <?= $escaper->escapeHtml(__('Phone')) ?>: <?= $escaper->escapeHtml($pos['phone']) ?><?= PHP_EOL ?>
- <?= $escaper->escapeHtml(__('Store Page')) ?>: <?= $escaper->escapeUrl($pos['url']) ?><?= PHP_EOL . PHP_EOL ?>

<?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($data['faq'])): ?>
## <?= __('Frequently Asked Questions') ?><?= PHP_EOL . PHP_EOL ?>
<?php foreach ($data['faq'] as $category): ?>
### <?= $escaper->escapeHtml($category['category_title']) ?><?= PHP_EOL . PHP_EOL ?>
<?php foreach ($category['questions'] as $question): ?>
**<?= __('Question') ?>: <?= $escaper->escapeHtml($question['title']) ?>**<?= PHP_EOL ?>

<?= __('Answer') ?>: <?= $escaper->escapeHtml($question['answer']) ?><?= PHP_EOL . PHP_EOL ?>
<?php endforeach; ?>
<?php endforeach; ?>
<?php endif; ?>

<?php if (!empty($data['social_media'])): ?>
## <?= __('Connect with Us on Social Media') ?><?= PHP_EOL . PHP_EOL ?>
<?php foreach ($data['social_media'] as $link): ?>
- [<?= $escaper->escapeHtml($link['name']) ?>](<?= $escaper->escapeUrl($link['url']) ?>)<?= PHP_EOL ?>
<?php endforeach; ?>
<?php endif; ?>

<?php if (!empty($data['additional_content'])): ?>
<?= $escaper->escapeHtml($data['additional_content']) ?>
<?php endif; ?>
